os:
- linux

language: go

go:
- 1.x
- tip

matrix:
  allow_failures:
  - go: tip

before_install:
- go get github.com/Masterminds/glide

install:
- glide install --strip-vendor

script:
- make
- make test
